import Link from "next/link";
import { Check } from "lucide-react";
import { HireEnquiryForm } from "@/components/hire/hire-enquiry-form";
import { HireFaq } from "@/components/hire/hire-faq";
import { HirePricingTable } from "@/components/hire/hire-pricing-table";
import { HireSelfServeForm } from "@/components/hire/hire-self-serve-form";
import { getHireCategoryImages } from "@/lib/hire-images";
import { FLEX_FAQS, FLEX_SETUP_FEE_GBP, type HirePricingCategoryId } from "@/lib/hire-pricing";
import { formatGBP } from "@/lib/products";
import { createMetadata, jsonLdScript, SITE } from "@/lib/seo";

export const revalidate = 300;
export const metadata = createMetadata({ title: "Flex Monthly Mobility Scooter & Wheelchair Hire | Mobility Station", description: "Flex monthly hire for scooters and wheelchairs. Servicing, batteries and breakdown cover included. Book online from Heathrow and Ferndown.", path: "/hire/flex", absoluteTitle: true });
export default async function FlexHirePage() {
  const imagesList=await getHireCategoryImages(); const images=Object.fromEntries(imagesList.map((img)=>[img.id,{src:img.src,alt:img.alt}])) as Record<HirePricingCategoryId,{src:string|null;alt:string}>;
  const breadcrumbLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE.url},{"@type":"ListItem",position:2,name:"Hire",item:`${SITE.url}/hire`},{"@type":"ListItem",position:3,name:"Flex hire",item:`${SITE.url}/hire/flex`}]}; const faqLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:FLEX_FAQS.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(breadcrumbLd)} /><script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(faqLd)} />
  <section className="border-b border-border bg-white"><div className="container-site py-14 md:py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">Flex monthly hire · 3+ months</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-extrabold leading-[0.98] tracking-[-0.045em] text-primary md:text-6xl lg:text-7xl">Use it monthly. We look after it.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted md:text-xl">Longer-term scooter and wheelchair hire with servicing, batteries and breakdown support included.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#book" className="rounded-full bg-accent px-7 py-3 font-semibold text-accent-foreground">Book Flex hire</a><a href="#prices" className="rounded-full border border-primary px-7 py-3 font-semibold text-primary">See monthly prices</a></div><p className="mt-6 text-sm text-muted">Only need it for under a month? <Link href="/hire/short-term" className="font-bold text-primary underline">See short-term hire</Link>.</p></div></section>
  <section className="border-b border-border py-14 md:py-20"><div className="container-site max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Included with Flex</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Support built in.</h2><ul className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{["Annual servicing and care","Replacement batteries when worn","Breakdown repairs","Loan machine if needed","Change model after 3 months"].map((item) => <li key={item} className="rounded-2xl border border-border p-5"><Check className="h-4 w-4 text-primary" /><p className="mt-4 text-sm font-semibold text-primary">{item}</p></li>)}</ul></div></section>
  <section className="border-b border-border bg-soft/55 py-14 md:py-20"><div className="container-site max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Payments</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">How Flex payment works.</h2><ol className="mt-9 grid gap-4 md:grid-cols-3">{[["01","Pay today",`First month + ${formatGBP(FLEX_SETUP_FEE_GBP)} set-up for delivery, setup and handover.`],["02","Then monthly","Pay one month in advance while you continue to use the equipment."],["03","Cancel after 3 months","After the initial three months, tell us when you no longer need it."]].map(([step,title,body]) => <li key={step} className="rounded-2xl border border-border bg-white p-6"><p className="text-xs font-bold text-muted">{step}</p><h3 className="mt-5 text-lg font-extrabold text-primary">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{body}</p></li>)}</ol></div></section>
  <section id="prices" className="scroll-mt-24 border-b border-border py-14 md:py-20"><div className="container-site"><HirePricingTable images={images} lockedMode="flex" /></div></section>
  <section className="border-b border-border py-14 md:py-20"><div className="container-site"><HireFaq title="Flex hire questions" faqs={FLEX_FAQS} /></div></section>
  <section id="book" className="scroll-mt-24 border-b border-border py-14 md:py-20"><div className="container-site grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Secure online booking</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Book Flex hire.</h2><p className="mt-4 text-muted">Pay the first month and set-up online. We deliver, set up and show you how to use the machine.</p><p className="mt-5 text-sm text-muted">Prefer to talk? Call <a href={SITE.phoneHref} className="font-bold text-primary">{SITE.phone}</a>. · <Link href="/hire/terms" className="font-semibold text-primary underline">Hire terms</Link></p></div><div className="rounded-[2rem] border border-border bg-soft/55 p-6 md:p-8"><HireSelfServeForm defaultHireType="flex" lockHireType /></div></div></section>
  <section id="enquiry-fallback" className="scroll-mt-24 bg-soft/55 py-14 md:py-16"><div className="container-site grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:gap-16"><div><h2 className="text-2xl font-extrabold text-primary">Want us to call first?</h2><p className="mt-3 text-muted">Send a short message if you’d rather speak before paying.</p></div><div className="rounded-2xl border border-border bg-white p-6 md:p-8"><HireEnquiryForm defaultHireType="flex" /></div></div></section></>;
}
