"use client";
import { useState } from "react";
import Image from "next/image";
import { Check, ShieldCheck, Truck, Phone, BatteryFull, Move, Plus } from "lucide-react";
import { sharedCheckoutPath, CHECKOUT_ORIGIN } from "@/lib/checkout-brands";

export type ErgoPackage = { batteries: number; price: number; was: number; variantId: string };
const money = (value: number) => new Intl.NumberFormat("en-GB", {style:"currency",currency:"GBP",maximumFractionDigits:0}).format(value);
export function ErgoFoldStore({ packages, productId, available, checkoutOrigin = CHECKOUT_ORIGIN }: { packages: ErgoPackage[]; productId: string; available: boolean; checkoutOrigin?: string }) {
  const [selected, setSelected] = useState(0);
  const [vat, setVat] = useState(false);
  const [photo, setPhoto] = useState(0);
  const pack = packages[selected];
  const photos = [{src:"https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/fc36591e-fab0-4345-8ae5-767610a7e45d.webp",alt:"ErgoFold Elite silver folding electric wheelchair, front three-quarter view", label:"Ready to go"},{src:"https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/0ff881c2-c21c-456e-a6f3-89a87972a644.webp",alt:"ErgoFold Elite folded down for transport",label:"Folded"},{src:"https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/fe77b1bc-cc38-41f3-84e3-c8237e732bfb.webp",alt:"ErgoFold Elite joystick and control display",label:"The controls"}];
  const checkout = checkoutOrigin + sharedCheckoutPath("ergofold", [{id:productId,slug:"ergofold-folding-power-chair",quantity:1,variantIds:[pack.variantId]}]);
  const factor = vat ? 1.2 : 1;
  return <div className="ergo-site">
    <div className="ergo-offer">A little more freedom. A lot less to pay. <strong>Save £1,000 ex VAT on every package.</strong></div>
    <header className="ergo-nav ergo-wrap"><a className="ergo-logo" href="#"><Image src="/ergofold/logo.png" alt="ErgoFold — Life without limits" width={300} height={90} unoptimized /></a><nav aria-label="Main navigation"><a href="#difference">The difference</a><a href="#details">The details</a><a href="#questions">Questions</a></nav><a href="#choose" className="ergo-button ergo-button-small">Choose your chair</a></header>
    <div className="ergo-main">
    <section className="ergo-hero ergo-wrap">
      <div className="ergo-hero-copy"><p className="ergo-eyebrow">THE PREMIUM FOLDING POWERCHAIR</p><h1>Life’s out there.<br/><span>Go get it.</span></h1><p className="ergo-lead">The café you love. A day by the coast. One more stop on the way home. Meet the ErgoFold Elite: smooth power, compact folding and room for bigger plans.</p><div className="ergo-price-line"><span>From</span><strong>{money(packages[0].price)}</strong><del>{money(packages[0].was)}</del><span className="ergo-saving">SAVE £1,000</span></div><p className="ergo-price-note">With VAT relief for eligible customers. {money(packages[0].price * 1.2)} including VAT.</p><div className="ergo-hero-actions"><a href="#choose" className="ergo-button">Find your freedom</a><a href="tel:08007723870" className="ergo-call"><Phone size={17}/>Talk to a real person</a></div><p className="ergo-small-trust"><Check size={16}/>Free UK delivery <span>•</span> UK specialist support</p></div>
      <div className="ergo-hero-image"><span className="ergo-hero-edition">E / 01<br/>ELITE SERIES</span><Image src="https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/fc36591e-fab0-4345-8ae5-767610a7e45d.webp" width={1024} height={1024} priority alt="ErgoFold Elite premium folding electric wheelchair"/><div className="ergo-range-badge"><span>GO FURTHER</span><strong>30<span> miles*</span></strong><small>With the three-battery package</small></div><span className="ergo-image-caption">Big on possibility. Small when folded.</span></div>
    </section>
    <section className="ergo-proof"><div className="ergo-wrap ergo-proof-grid"><div><BatteryFull/><span><strong>1, 2 or 3 batteries</strong>Your day. Your range.</span></div><div><Move/><span><strong>Folds in seconds</strong>Ready for the next journey.</span></div><div><ShieldCheck/><span><strong>UK aftercare</strong>People you can speak to.</span></div><div><Truck/><span><strong>Free UK delivery</strong>From our team to your door.</span></div></div></section>
    <section id="difference" className="ergo-section ergo-wrap"><div className="ergo-section-heading"><p className="ergo-eyebrow">FEEL THE DIFFERENCE</p><h2>A proper powerchair.<br/>With a portable side.</h2><p>Thoughtful engineering for everyday journeys. Because the way your chair feels matters just as much as where it takes you.</p></div><div className="ergo-feature-grid"><article><span className="ergo-feature-number">01</span><h3>Power that feels composed.</h3><p>Twin 250W motors and intuitive joystick control put confident, responsive movement at your fingertips.</p></article><article><span className="ergo-feature-number">02</span><h3>Three ways to find your flow.</h3><p>Three driving modes let you choose the feel that suits you. Try the controls with our team and find your favourite.</p></article><article><span className="ergo-feature-number">03</span><h3>Made for the long way round.</h3><p>Choose up to three lithium batteries. More range for more of the places, people and moments you love.</p></article></div></section>
    <section className="ergo-fold-section"><div className="ergo-wrap ergo-fold-grid"><div className="ergo-fold-photo"><Image src="https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/0ff881c2-c21c-456e-a6f3-89a87972a644.webp" width={1024} height={1024} alt="ErgoFold Elite compactly folded for storage"/></div><div><p className="ergo-eyebrow">TAKE LIFE WITH YOU</p><h2>All that capability.<br/>Folded down.</h2><p>From a day out to putting it away at home, the Elite folds into a compact shape. Less space taken up. More possibilities opened up.</p><ul className="ergo-checklist"><li><Check/>Folding aluminium frame</li><li><Check/>Flip-up armrests for easier access</li><li><Check/>Expandable lithium battery system</li><li><Check/>Support from a UK mobility specialist</li></ul><p className="ergo-note">Ask us to check the folded fit and lifting weight for your car before ordering. A demonstration is the best way to find out what works for you.</p><a className="ergo-text-link" href="https://mobilitystation.co.uk/book-a-demo?product=ergofold-folding-power-chair">Arrange a demonstration</a></div></div></section>
    <section id="choose" className="ergo-section ergo-wrap"><div className="ergo-section-heading ergo-centred"><p className="ergo-eyebrow">ONE GREAT CHAIR. YOUR KIND OF DAY.</p><h2>How far will you go?</h2><p>Choose your battery package. Every option includes the ErgoFold Elite and free UK delivery.</p></div><div className="ergo-buy-grid"><div className="ergo-gallery"><div className="ergo-gallery-main"><Image key={photo} src={photos[photo].src} width={1024} height={1024} alt={photos[photo].alt}/></div><div className="ergo-gallery-tabs" role="group" aria-label="Product images">{photos.map((p,i)=><button type="button" key={p.src} onClick={()=>setPhoto(i)} aria-pressed={photo===i}>{p.label}</button>)}</div></div><div className="ergo-configurator"><h3>ErgoFold Elite</h3><p className="ergo-config-sub">Premium folding electric wheelchair</p><fieldset><legend>Choose your batteries</legend>{packages.map((p,i)=><label key={p.batteries} className={`ergo-package ${selected===i?"is-selected":""}`}><input type="radio" name="batteries" checked={selected===i} onChange={()=>setSelected(i)}/><span className="ergo-radio"/><span className="ergo-package-copy"><strong>{p.batteries} {p.batteries===1?"battery":"batteries"}{p.batteries===3?<em>MAXIMUM RANGE</em>:null}</strong><small>Up to {p.batteries*10} miles* · {p.batteries} × 10Ah lithium</small></span><span className="ergo-package-price"><strong>{money(p.price*factor)}</strong><del>{money(p.was*factor)}</del></span></label>)}</fieldset><label className="ergo-vat"><input type="checkbox" checked={vat} onChange={e=>setVat(e.target.checked)}/>Show prices including VAT</label><div className="ergo-order-total" aria-live="polite"><span>Your package<strong>{money(pack.price*factor)}</strong></span><span className="ergo-saving">SAVE {money((pack.was-pack.price)*factor)}</span></div><p className="ergo-price-note">{vat?"Including 20% VAT.":"With VAT relief. Eligibility declaration at checkout."}</p>{available?<a href={checkout} className="ergo-button ergo-buy">Continue to secure checkout</a>:<a href="tel:08007723870" className="ergo-button ergo-buy">Call to order your Elite</a>}<p className="ergo-checkout-note"><ShieldCheck size={15}/>Secure checkout operated by Mobility Station</p><p className="ergo-range-note">*Maximum advertised range with 1 / 2 / 3 batteries. Actual range depends on user weight, terrain, temperature and driving style. Eezychair quotes lower ranges of 8 / 15 / 23 miles; speak to us about your needs.</p></div></div></section>
    <section id="details" className="ergo-spec-section"><div className="ergo-wrap ergo-spec-grid"><div><p className="ergo-eyebrow">THE DETAILS THAT MATTER</p><h2>Thought through.<br/>Ready to explore.</h2><Image src="https://pub-d0fa88fa71f044d9a9fc37a3c9d5fe47.r2.dev/stock-images/fe77b1bc-cc38-41f3-84e3-c8237e732bfb.webp" width={1024} height={1024} alt="Close-up of the ErgoFold joystick controller" className="ergo-controls-photo"/></div><dl><div><dt>Drive</dt><dd>Twin 250W motors</dd></div><div><dt>Driving modes</dt><dd>3 selectable modes</dd></div><div><dt>Battery options</dt><dd>1, 2 or 3 × 10Ah lithium</dd></div><div><dt>Maximum user weight</dt><dd>150kg</dd></div><div><dt>Frame</dt><dd>Folding aluminium</dd></div><div><dt>Wheels</dt><dd>8-inch front / 12-inch rear</dd></div><div><dt>Controls</dt><dd>Joystick</dd></div><div><dt>Delivery</dt><dd>Free UK delivery</dd></div></dl></div></section>
    <section id="questions" className="ergo-section ergo-wrap ergo-faq"><div><p className="ergo-eyebrow">LET’S MAKE IT SIMPLE</p><h2>A few good questions.</h2><p>Choosing a chair is personal.<br/>We’re here to help you get it right.</p><a href="tel:08007723870" className="ergo-text-link">Call 0800 772 3870</a></div><div>{[
      ["Which battery package should I choose?","One battery keeps the price lowest for shorter outings. Two gives you more flexibility, while three offers the longest advertised range. Choose with a comfortable reserve for your return journey; range varies with real-world use."],
      ["Can I claim VAT relief?","Qualifying customers buying an eligible mobility product for personal or domestic use can complete a VAT-relief declaration in our shared checkout. Prices default to the VAT-relief price; use the toggle above to see prices including VAT. Contact our team if you are unsure."],
      ["Will it fit in my car?","The chair folds for transport, but every boot and lifting situation is different. Ask our team to check the folded dimensions and lifting weight with you, or arrange a demonstration before ordering."],
      ["Who takes care of my order?","Your order is handled by Adaptation Station Ltd, trading as Mobility Station. You’ll use our shared secure checkout, with UK support for product advice, delivery and aftercare."],
      ["Can I try it before buying?","Yes—contact Mobility Station to arrange a demonstration and check availability. We can talk through the controls, comfort, folding and the right battery package for you."],
    ].map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
    <section className="ergo-final"><div className="ergo-wrap"><p className="ergo-eyebrow">MORE LIFE. LESS HOLDING BACK.</p><h2>Your next chapter<br/>starts with a little freedom.</h2><a href="#choose" className="ergo-button">Choose your ErgoFold Elite</a><p>From £995 with VAT relief · Free UK delivery</p></div></section>
    </div>
    <footer className="ergo-footer ergo-wrap"><div><a href="#" className="ergo-logo"><Image src="/ergofold/logo.png" alt="ErgoFold — Life without limits" width={300} height={90} unoptimized /></a><p>This website is owned and operated by Adaptation Station Ltd,<br/>trading as Mobility Station.</p></div><div><strong>Real people. Ready to help.</strong><a href="tel:08007723870">0800 772 3870</a><a href="mailto:hello@mobilitystation.co.uk">hello@mobilitystation.co.uk</a></div><div><a href="https://mobilitystation.co.uk/terms">Terms &amp; returns</a><a href="https://mobilitystation.co.uk/privacy-policy">Privacy policy</a><a href="https://mobilitystation.co.uk/vat-relief">VAT relief</a></div><p className="ergo-copyright">© {new Date().getFullYear()} Adaptation Station Ltd. All prices in GBP. VAT relief subject to eligibility.</p></footer>
    <div className="ergo-mobile-bar"><span>ErgoFold Elite<strong>From £995</strong></span><a href="#choose" className="ergo-button ergo-button-small">Choose yours</a></div>
  </div>;
}
