import Link from "next/link";
import { Check } from "lucide-react";
import { HireFaq } from "@/components/hire/hire-faq";
import { HirePricingTable } from "@/components/hire/hire-pricing-table";
import { HireSelfServeForm } from "@/components/hire/hire-self-serve-form";
import { getHireCategoryImages } from "@/lib/hire-images";
import { LOCAL_DELIVERY_FEE_GBP, LOCAL_DELIVERY_MILES, SHORT_TERM_FAQS, WIDER_DELIVERY_FROM_GBP, type HirePricingCategoryId } from "@/lib/hire-pricing";
import { formatGBP } from "@/lib/products";
import { createMetadata, jsonLdScript, SITE } from "@/lib/seo";

export const revalidate = 300;
export const metadata = createMetadata({ title: "Short-Term Mobility Scooter & Wheelchair Hire | Mobility Station", description: "Hire a mobility scooter or wheelchair for 3 to 28 days. Book and pay online. Free collection from Heathrow or Ferndown, or delivery available.", path: "/hire/short-term", absoluteTitle: true });
export default async function ShortTermHirePage() {
  const imagesList = await getHireCategoryImages(); const images = Object.fromEntries(imagesList.map((img) => [img.id,{src:img.src,alt:img.alt}])) as Record<HirePricingCategoryId,{src:string|null;alt:string}>;
  const breadcrumbLd = { "@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE.url},{"@type":"ListItem",position:2,name:"Hire",item:`${SITE.url}/hire`},{"@type":"ListItem",position:3,name:"Short-term hire",item:`${SITE.url}/hire/short-term`}]}; const faqLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:SHORT_TERM_FAQS.map((faq)=>({"@type":"Question",name:faq.q,acceptedAnswer:{"@type":"Answer",text:faq.a}}))};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(breadcrumbLd)} /><script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(faqLd)} />
  <section className="border-b border-border bg-white"><div className="container-site py-14 md:py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">Short-term hire · 3–28 days</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-extrabold leading-[0.98] tracking-[-0.045em] text-primary md:text-6xl lg:text-7xl">Hire for days, not forever.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted md:text-xl">Scooters and wheelchairs from 3 to 28 days, with free branch collection or delivery options from Heathrow and Ferndown.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#book" className="rounded-full bg-accent px-7 py-3 font-semibold text-accent-foreground">Book short-term hire</a><a href="#prices" className="rounded-full border border-primary px-7 py-3 font-semibold text-primary">See prices</a></div><p className="mt-6 text-sm text-muted">Need it longer? <Link href="/hire/flex" className="font-bold text-primary underline">See Flex monthly hire</Link>.</p></div></section>
<section id="prices" className="scroll-mt-24 border-b border-border py-14 md:py-20"><div className="container-site"><HirePricingTable images={images} lockedMode="short" /></div></section>
  <section className="border-b border-border bg-soft/55 py-14 md:py-16"><div className="container-site max-w-4xl"><h2 className="text-3xl font-extrabold tracking-tight text-primary">Delivery or free collection.</h2><ul className="mt-7 grid gap-4 md:grid-cols-3">{[["Collect free","Heathrow or Ferndown, by appointment."],["Local delivery",`${formatGBP(LOCAL_DELIVERY_FEE_GBP)} within ${LOCAL_DELIVERY_MILES} miles, including basic handover.`],["Further away",`${formatGBP(WIDER_DELIVERY_FROM_GBP)} for around 15–40 miles. Outside that, please collect or call.`]].map(([title,body]) => <li key={title} className="border-t border-border pt-5"><Check className="h-4 w-4 text-primary" /><h3 className="mt-4 font-bold text-primary">{title}</h3><p className="mt-2 text-sm text-muted">{body}</p></li>)}</ul></div></section>
  <section className="border-b border-border py-14 md:py-20"><div className="container-site"><HireFaq title="Short-term hire questions" faqs={SHORT_TERM_FAQS} /></div></section>
  <section id="book" className="scroll-mt-24 border-b border-border py-14 md:py-20"><div className="container-site grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Secure online booking</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Book short-term hire.</h2><p className="mt-4 text-muted">Fill in the details and pay securely. We’ll match a suitable machine and arrange delivery or collection.</p><p className="mt-5 text-sm text-muted">Prefer to talk? Call <a href={SITE.phoneHref} className="font-bold text-primary">{SITE.phone}</a>. · <Link href="/hire/terms" className="font-semibold text-primary underline">Hire terms</Link></p></div><div className="border-t border-border pt-6"><HireSelfServeForm defaultHireType="short" lockHireType /></div></div></section>
  <section id="enquiry-fallback" className="container-site py-8"><p className="text-muted">Want to talk before booking? <Link href="/contact?interest=hire&mode=callback#enquire" className="font-semibold text-primary underline underline-offset-4">Ask our team to call you</Link>.</p></section></>;
}
