import { Check } from "lucide-react";
import { CarePlanSignupDialog } from "@/components/care-plans/care-plan-signup-dialog";
import { buttonVariants } from "@/components/ui/button";
import { CARE_PLANS, formatCarePlanPrice } from "@/lib/carePlans";
import { cn } from "@/lib/utils";

export function CarePlansSection() {
  return <section id="care-plans" className="scroll-mt-24 border-y border-border bg-soft/55 py-14 md:py-20"><div className="container-site"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Mobility Care Plans</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Ongoing support, made simple.</h2><p className="mt-4 text-base leading-relaxed text-muted md:text-lg">Monthly plans from our Heathrow and Ferndown workshops, with priority booking and savings on maintenance support.</p></div><ul className="mt-10 grid gap-5 lg:grid-cols-3 lg:items-stretch">{CARE_PLANS.map((plan) => <li key={plan.key}><article className={cn("relative flex h-full flex-col rounded-[2rem] border p-7", plan.mostPopular ? "border-primary bg-primary text-white" : "border-border bg-white")}>{plan.mostPopular ? <span className="absolute right-5 top-5 rounded-full bg-accent px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-accent-foreground">Most popular</span> : null}<h3 className={cn("text-2xl font-extrabold", plan.mostPopular ? "text-white" : "text-primary")}>{plan.name}</h3><p className={cn("mt-2 text-sm", plan.mostPopular ? "text-white/65" : "text-muted")}>{plan.tagline}</p><p className="mt-6 flex items-baseline gap-1"><span className={cn("text-4xl font-extrabold tracking-tight", plan.mostPopular ? "text-white" : "text-primary")}>{plan.priceLabel}</span><span className={cn("text-sm font-semibold", plan.mostPopular ? "text-white/55" : "text-muted")}>/month</span></p><ul className="mt-7 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className={cn("flex gap-2.5 text-sm leading-snug", plan.mostPopular ? "text-white/80" : "text-foreground/90")}><Check className={cn("mt-0.5 h-4 w-4 shrink-0", plan.mostPopular ? "text-accent-on-dark" : "text-accent")} aria-hidden /><span>{feature}</span></li>)}</ul><div className="mt-8"><CarePlanSignupDialog plan={plan} triggerClassName={cn(buttonVariants({ size: "lg" }), "w-full rounded-full", plan.mostPopular && "bg-accent text-accent-foreground hover:bg-accent-hover")}>Choose {plan.name}</CarePlanSignupDialog></div><ul className={cn("mt-5 space-y-1 border-t pt-4", plan.mostPopular ? "border-white/15" : "border-border")}>{plan.terms.map((term) => <li key={term} className={cn("text-xs leading-relaxed", plan.mostPopular ? "text-white/50" : "text-muted")}>{term}</li>)}</ul><p className="sr-only">{formatCarePlanPrice(plan)}</p></article></li>)}</ul></div></section>;
}
