import Link from "next/link";
import { EnquiryForm } from "@/components/forms/enquiry-form";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "Book a Service | Repairs & Support", description: "Book a mobility scooter or wheelchair service with Mobility Station. Heathrow & Ferndown support, plus collection options.", path: "/book-a-service" });

export default function BookAServicePage() {
  return <>
    <section className="border-b border-border bg-white"><div className="container-site py-14 md:py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">Mobility Station · Service &amp; repair</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-extrabold leading-[0.98] tracking-[-0.045em] text-primary md:text-6xl lg:text-7xl">Get it looked after.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted md:text-xl">Tell us about your scooter, wheelchair or vehicle adaptation and we’ll arrange the right support from Heathrow or Ferndown.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#form" className="rounded-full bg-accent px-7 py-3 font-semibold text-accent-foreground">Book service</a><Link href="/servicing#care-plans" className="rounded-full border border-primary px-7 py-3 font-semibold text-primary hover:bg-primary hover:text-white">View Care Plans</Link></div></div></section>
    <section id="form" className="py-14 md:py-20"><div className="container-site grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Workshop support</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Service booking request.</h2><p className="mt-4 text-muted">Give us the equipment details and what is happening. The team can then arrange workshop, collection or other support as appropriate.</p><p className="mt-6 text-sm text-muted">Want ongoing cover? See <Link href="/servicing#care-plans" className="font-semibold text-primary underline underline-offset-2">Mobility Care Plans</Link> from £12.99/month, or <Link href="/contact" className="font-semibold text-primary underline underline-offset-2">contact the team</Link>.</p></div><div className="rounded-[2rem] border border-border bg-soft/55 p-6 md:p-8"><EnquiryForm enquiryType="service" title="Service booking request" defaultInterest="Service / repair" /></div></div></section>
  </>;
}
