"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from "react";
import { ChevronDown, MapPin, Menu, Phone, PhoneCall, X } from "lucide-react";
import { CartButton } from "@/components/cart/cart-drawer";
import { EnquiryDialog } from "@/components/forms/enquiry-dialog";
import { HeaderSearch } from "@/components/layout/header-search";
import { Button, buttonVariants } from "@/components/ui/button";
import { SITE_NAV, navItemIsActive, type NavItem } from "@/lib/site-nav";
import { SITE } from "@/lib/seo";
import { cn } from "@/lib/utils";

function isActivePath(pathname: string, href: string) { const base = href.split("?")[0].split("#")[0]; return pathname === base || (base !== "/" && pathname.startsWith(`${base}/`)); }

export function SiteHeader() {
  const [open, setOpen] = useState(false); const [desktopOpenId, setDesktopOpenId] = useState<string | null>(null); const [mobileOpenId, setMobileOpenId] = useState<string | null>(null); const pathname = usePathname(); const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const navRef = useRef<HTMLElement>(null);
  const clearCloseTimer = useCallback(() => { if (closeTimer.current) { clearTimeout(closeTimer.current); closeTimer.current = null; } }, []);
  const scheduleClose = useCallback(() => { clearCloseTimer(); closeTimer.current = setTimeout(() => setDesktopOpenId(null), 120); }, [clearCloseTimer]);
  const openMenu = useCallback((id: string) => { clearCloseTimer(); setDesktopOpenId(id); }, [clearCloseTimer]);
  useEffect(() => { setOpen(false); setDesktopOpenId(null); setMobileOpenId(null); }, [pathname]);
  useEffect(() => { if (!open && !desktopOpenId) return; const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") { setOpen(false); setDesktopOpenId(null); setMobileOpenId(null); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [open, desktopOpenId]);
  useEffect(() => { if (!desktopOpenId) return; const onPointer = (e: MouseEvent) => { if (!navRef.current?.contains(e.target as Node)) setDesktopOpenId(null); }; document.addEventListener("mousedown", onPointer); return () => document.removeEventListener("mousedown", onPointer); }, [desktopOpenId]);
  useEffect(() => { if (!open) return; const prev = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = prev; }; }, [open]);

  return <header className="sticky top-0 z-50 bg-white shadow-[0_8px_28px_-20px_rgba(0,0,0,0.28)]">
    <div className="bg-primary text-primary-foreground"><div className="container-site flex h-8 items-center justify-between gap-3 text-xs font-medium"><p className="flex min-w-0 items-center gap-1.5 truncate"><MapPin className="hidden h-3.5 w-3.5 text-accent sm:block" aria-hidden /><span className="sm:hidden">Heathrow &amp; Ferndown</span><span className="hidden sm:inline">Heathrow &amp; Ferndown <span className="mx-2 text-white/25">·</span><Link href="/book-a-demo#demo-terms" className="text-white/70 hover:text-accent">Free branch demos · Home demos £195*</Link></span></p><a href={SITE.phoneHref} className="inline-flex shrink-0 items-center gap-1.5 tabular-nums hover:text-accent"><Phone className="hidden h-3.5 w-3.5 sm:block" aria-hidden />{SITE.phone}</a></div></div>
    <div className="border-b border-border bg-white"><div className="container-site flex h-[4.6rem] items-center gap-3 md:h-[4.9rem] md:gap-6"><Link href="/" className="flex shrink-0 items-center" onClick={() => setOpen(false)}><img src="/brand/mobility-station-wordmark.png?v=20260830" alt="Mobility Station" width={800} height={300} className="h-11 w-auto md:h-12" decoding="async" fetchPriority="high" /></Link><HeaderSearch className="mx-auto hidden min-w-0 max-w-lg flex-1 md:block" /><div className="ml-auto flex shrink-0 items-center gap-2"><div className="hidden items-center gap-2 sm:flex"><EnquiryDialog mode="callback" title="Request a callback" triggerClassName={cn(buttonVariants({ variant: "outline", size: "sm" }), "rounded-full border-border bg-white text-primary hover:border-primary")}><PhoneCall className="h-4 w-4" aria-hidden /><span className="hidden lg:inline">Request a callback</span><span className="lg:hidden">Callback</span></EnquiryDialog><Link href="/book-a-demo" className={cn(buttonVariants({ size: "sm" }), "hidden rounded-full sm:inline-flex")}><span className="lg:hidden">Demo</span><span className="hidden lg:inline">Book a demo</span></Link></div><CartButton /><Button type="button" variant="ghost" size="icon" className="lg:hidden" aria-expanded={open} aria-controls="mobile-nav" aria-label={open ? "Close menu" : "Open menu"} onClick={() => setOpen((v) => !v)}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</Button></div></div></div>
    <nav ref={navRef} className="relative hidden border-b border-border bg-white lg:block" aria-label="Primary" onMouseLeave={scheduleClose}><div className="container-site flex h-11 items-stretch gap-0.5">{SITE_NAV.map((item) => <DesktopNavItem key={item.type === "menu" ? item.id : item.href} item={item} pathname={pathname} openId={desktopOpenId} onOpen={openMenu} onScheduleClose={scheduleClose} onClearClose={clearCloseTimer} onClose={() => setDesktopOpenId(null)} />)}</div></nav>
    {open ? <div id="mobile-nav" className="max-h-[min(78vh,40rem)] overflow-y-auto border-t border-border bg-white shadow-lg lg:hidden"><div className="container-site space-y-4 py-4"><HeaderSearch size="sm" className="w-full md:hidden" onSubmitExtra={() => setOpen(false)} /><nav className="flex flex-col gap-1" aria-label="Mobile">{SITE_NAV.map((item) => <MobileNavItem key={item.type === "menu" ? item.id : item.href} item={item} pathname={pathname} openId={mobileOpenId} setOpenId={setMobileOpenId} onNavigate={() => setOpen(false)} />)}</nav><div className="grid gap-2 border-t border-border pt-4 sm:hidden"><EnquiryDialog mode="callback" title="Request a callback" triggerClassName={cn(buttonVariants({ variant: "outline" }), "w-full rounded-full")}><PhoneCall className="h-4 w-4" aria-hidden />Request a callback</EnquiryDialog><Link href="/book-a-demo" className={cn(buttonVariants(), "w-full rounded-full")} onClick={() => setOpen(false)}>Book a demo</Link><Link href="/contact" className="block rounded-lg px-3 py-3 text-center text-sm font-semibold text-primary hover:bg-soft" onClick={() => setOpen(false)}>Contact</Link></div></div></div> : null}
  </header>;
}

function DesktopNavItem({ item, pathname, openId, onOpen, onScheduleClose, onClearClose, onClose }: { item: NavItem; pathname: string; openId: string | null; onOpen: (id:string)=>void; onScheduleClose:()=>void; onClearClose:()=>void; onClose:()=>void }) {
  const active = navItemIsActive(pathname, item);
  if (item.type === "link") return <Link href={item.href} className={cn("relative flex items-center px-3.5 text-[13px] font-semibold tracking-wide transition-colors", active ? "text-primary" : "text-muted hover:text-primary")}>{item.label}<span className={cn("absolute inset-x-3.5 bottom-0 h-0.5 rounded-full bg-accent transition-opacity", active ? "opacity-100" : "opacity-0")} /></Link>;
  const isOpen = openId === item.id; const panelId = `nav-panel-${item.id}`;
  return <div className="relative flex" onMouseEnter={() => onOpen(item.id)} onMouseLeave={onScheduleClose}><div className={cn("group relative inline-flex h-full items-center", active || isOpen ? "text-primary" : "text-muted hover:text-primary")}><Link href={item.href} className="flex h-full items-center pl-3.5 pr-1 text-[13px] font-semibold tracking-wide" onFocus={() => onOpen(item.id)}>{item.label}</Link><button type="button" className="flex h-full items-center pr-3" aria-expanded={isOpen} aria-controls={panelId} aria-haspopup="true" aria-label={`${item.label} menu`} onClick={() => isOpen ? onScheduleClose() : onOpen(item.id)} onFocus={() => { onClearClose(); onOpen(item.id); }} onKeyDown={(e: ReactKeyboardEvent) => { if (e.key === "ArrowDown") { e.preventDefault(); onOpen(item.id); onClearClose(); } }}><ChevronDown className={cn("h-3.5 w-3.5 opacity-70 transition-transform", isOpen && "rotate-180")} /></button><span className={cn("pointer-events-none absolute inset-x-3.5 bottom-0 h-0.5 rounded-full bg-accent transition-opacity", active || isOpen ? "opacity-100" : "opacity-0 group-hover:opacity-70")} /></div>{isOpen ? <div id={panelId} role="menu" className="absolute left-0 top-full z-50 pt-1" onMouseEnter={() => onOpen(item.id)}><div className="min-w-[14rem] overflow-hidden rounded-xl border border-border bg-white py-2 shadow-[0_18px_45px_-20px_rgba(0,0,0,0.3)]">{item.links.map((link) => { const linkActive = isActivePath(pathname, link.href); return <Link key={link.href + link.label} role="menuitem" href={link.href} onClick={onClose} className={cn("block px-4 py-2.5 text-[13px] font-semibold", linkActive ? "bg-soft text-primary" : "text-primary hover:bg-soft")}>{link.label}</Link>; })}</div></div> : null}</div>;
}

function MobileNavItem({ item, pathname, openId, setOpenId, onNavigate }: { item: NavItem; pathname: string; openId: string | null; setOpenId:(id:string|null)=>void; onNavigate:()=>void }) {
  const active = navItemIsActive(pathname, item);
  if (item.type === "link") return <Link href={item.href} className={cn("rounded-lg px-3.5 py-2.5 text-sm font-semibold", active ? "bg-primary text-white" : "text-primary hover:bg-soft")} onClick={onNavigate}>{item.label}</Link>;
  const isOpen = openId === item.id;
  return <div className="overflow-hidden rounded-lg border border-border"><div className="flex items-stretch"><Link href={item.href} className={cn("flex-1 px-3.5 py-2.5 text-sm font-semibold", active ? "bg-primary text-white" : "bg-white text-primary hover:bg-soft")} onClick={onNavigate}>{item.label}</Link><button type="button" className={cn("flex w-11 items-center justify-center border-l border-border", active ? "bg-primary text-white" : "bg-white text-primary hover:bg-soft")} aria-expanded={isOpen} aria-label={`${isOpen ? "Collapse" : "Expand"} ${item.label}`} onClick={() => setOpenId(isOpen ? null : item.id)}><ChevronDown className={cn("h-4 w-4 transition-transform", isOpen && "rotate-180")} /></button></div>{isOpen ? <ul className="border-t border-border bg-soft/30 py-1">{item.links.map((link) => <li key={link.href + link.label}><Link href={link.href} className="block px-3.5 py-2 text-sm font-semibold text-primary hover:bg-white" onClick={onNavigate}>{link.label}</Link></li>)}</ul> : null}</div>;
}
