import Link from "next/link";
import { MapPin, Phone } from "lucide-react";
import { BranchMap } from "@/components/sections/branch-map";
import { CtaFooter } from "@/components/sections/cta-footer";
import { ServiceAreaChecker } from "@/components/service-area/service-area-checker";
import { getBranches } from "@/lib/data";
import { createMetadata, jsonLdScript, SITE } from "@/lib/seo";

export const metadata = createMetadata({ title: "Locations | Heathrow & Ferndown", description: "Visit Mobility Station in Heathrow or Ferndown, or book a home demonstration. Opening hours, addresses, phone numbers and postcode coverage.", path: "/locations" });

export default async function LocationsPage() {
  const branches = await getBranches();
  const jsonLd = [...branches.map((branch) => ({ "@context": "https://schema.org", "@type": "LocalBusiness", name: `Mobility Station ${branch.name}`, telephone: branch.phone, email: branch.email, url: `${SITE.url}/locations`, address: { "@type": "PostalAddress", streetAddress: [branch.addressLine1, branch.addressLine2].filter(Boolean).join(", "), addressLocality: branch.addressLocality, postalCode: branch.postalCode, addressCountry: "GB" }, geo: { "@type": "GeoCoordinates", latitude: branch.lat, longitude: branch.lng } })), { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE.url }, { "@type": "ListItem", position: 2, name: "Locations", item: `${SITE.url}/locations` }] }];
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(jsonLd)} />
    <section className="border-b border-border bg-white"><div className="container-site py-14 md:py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">Mobility Station · Visit us</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-extrabold leading-[0.98] tracking-[-0.045em] text-primary md:text-6xl lg:text-7xl">Two branches. One standard of care.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted md:text-xl">Visit Heathrow or Ferndown for demonstrations, mobility equipment and specialist vehicle adaptations — with parking and step-free access.</p></div></section>
    <section className="py-12 md:py-16"><div className="container-site grid gap-5 md:grid-cols-2">{branches.map((branch) => <article key={branch.id} className="rounded-[2rem] border border-border bg-white p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Mobility Station</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary">{branch.name}</h2><div className="mt-6 flex gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-primary" aria-hidden /><p className="text-sm leading-relaxed text-muted">{branch.addressLine1}{branch.addressLine2 ? <>, {branch.addressLine2}</> : null}<br />{branch.addressLocality}, {branch.postalCode}</p></div><a href={`tel:${branch.phone.replace(/\s/g, "")}`} className="mt-5 inline-flex items-center gap-2 text-lg font-bold text-primary"><Phone className="h-4 w-4" aria-hidden />{branch.phone}</a><div className="mt-6 border-t border-border pt-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted">Opening hours</p><ul className="mt-3 space-y-1.5 text-sm text-muted">{branch.openingHours.map((line) => <li key={line}>{line}</li>)}</ul></div></article>)}</div></section>
    <BranchMap branches={branches} />
    <section className="border-t border-border bg-soft/55 py-14 md:py-20"><div className="container-site max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Home visits &amp; delivery</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">Do we cover you?</h2><p className="mt-3 text-muted">Check your postcode for home demonstrations, local delivery and collection. Large equipment ships nationwide on a pallet.</p><div className="mt-8 rounded-2xl border border-border bg-white p-5 md:p-6"><ServiceAreaChecker /></div><p className="mt-6 text-sm text-muted">See <Link href="/service-area" className="font-semibold text-primary underline underline-offset-2">call-out bands and the towns we cover</Link>, or read our <Link href="/delivery" className="font-semibold text-primary underline underline-offset-2">delivery information</Link>.</p></div></section>
    <CtaFooter />
  </>;
}
