"use client";
import Link from "next/link";
import { BrandLogo } from "@/components/product/brand-logo";
import { CatalogImage } from "@/components/product/catalog-image";
import { MotabilityLogo } from "@/components/product/motability-logo";
import { EnquiryDialog } from "@/components/forms/enquiry-dialog";
import { getBrandLogo } from "@/lib/brand-logos";
import { formatGBP, primaryImage, type ProductListItem } from "@/lib/products";
export function MotabilityProductCard({product}:{product:ProductListItem}) { const img=primaryImage(product); const weekly=product.motability_weekly_price!=null&&product.motability_weekly_price>0?product.motability_weekly_price:null; const freeOnScheme=product.motability_price===0; return <article className="flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-white transition-all duration-200 hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-[0_18px_40px_-28px_rgba(0,0,0,0.3)]"><Link href={`/products/${product.slug}?from=motability`} className="group block flex-1"><div className="relative aspect-square overflow-hidden bg-soft/30"><CatalogImage src={img} alt={product.name} fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 33vw, 50vw" className="object-contain p-3 transition-transform duration-300 group-hover:scale-[1.025]"/><div className="absolute left-3 top-3 rounded-full bg-white/95 px-2.5 py-1.5 shadow-sm"><MotabilityLogo height={20}/></div></div><div className="p-5">{product.category?<p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted">{product.category}</p>:getBrandLogo(product.manufacturer)?<BrandLogo manufacturer={product.manufacturer} height={20}/>:product.manufacturer?<p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted">{product.manufacturer}</p>:null}<h3 className="mt-3 min-h-[2.75rem] line-clamp-2 text-[15px] font-bold leading-snug text-primary">{product.name}</h3><div className="mt-5 border-t border-border pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted">Motability scheme price</p>{weekly!=null?<p className="mt-1 flex items-baseline gap-1.5"><span className="text-2xl font-extrabold text-primary">{formatGBP(weekly)}</span><span className="text-sm font-semibold text-muted">/ week</span></p>:freeOnScheme?<p className="mt-1 text-2xl font-extrabold text-primary">£0 / week</p>:<p className="mt-1 text-lg font-bold text-primary">Weekly price on request</p>}</div></div></Link><div className="px-5 pb-5"><EnquiryDialog mode="callback" title="Contact us about this model" defaultTopic="Motability" productSlug={product.slug} productLabel={product.name} triggerClassName="block w-full rounded-full bg-accent px-3 py-2.5 text-center text-sm font-semibold text-accent-foreground hover:bg-accent-hover">Contact us about this model</EnquiryDialog></div></article>; }
