import Link from "next/link";
import { AlertTriangle, CheckCircle2, FileText, HelpCircle, ShieldCheck } from "lucide-react";
import { CtaFooter } from "@/components/sections/cta-footer";
import { VAT_DECLARATION } from "@/lib/cart";
import { createMetadata, jsonLdScript } from "@/lib/seo";

export const metadata = createMetadata({ title: "VAT Relief on Mobility Products", description: "Save 20% with VAT relief on mobility scooters, wheelchairs and daily living aids. Check if you qualify and how to claim at checkout.", path: "/vat-relief" });
const qualifyingConditions = ["A physical disability", "A chronic illness or condition", "A mental health condition", "A terminal illness", "Blindness or partial sight", "Deafness or hearing impairment", "A learning disability", "Mobility impairment"];
const faqs = [
  { q: "What products qualify for VAT relief?", a: "Products designed to assist with a disability or chronic condition qualify, including mobility scooters, powered and manual wheelchairs, vehicle adaptations, and related accessories. Batteries and chargers qualify when collected and fitted at our workshop." },
  { q: "Do I need proof of my disability?", a: "No. You do not need to provide medical evidence at purchase. You sign a declaration confirming you have a qualifying condition. HMRC may request evidence later." },
  { q: "Can I claim VAT relief on behalf of someone else?", a: "Yes. If you are purchasing for a disabled person, the product can still qualify as long as it is for their personal use." },
  { q: "What happens if I'm not eligible?", a: "If you do not have a qualifying condition, VAT is charged at the standard rate of 20%. Falsely claiming VAT relief is a criminal offence." },
  { q: "How does it work at checkout?", a: "Tick the VAT exemption box, select the nature of your disability or chronic condition, and confirm the digital declaration. VAT is then removed from your order total." },
  { q: "I'm elderly but don't have a disability — do I qualify?", a: "No. Being elderly alone does not qualify. You must have a qualifying disability or chronic condition. Age-related conditions that are disabling may qualify." },
];

export default function VatReliefPage() {
  const faqLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.q, acceptedAnswer: { "@type": "Answer", text: faq.a } })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(faqLd)} />
    <section className="border-b border-border bg-white"><div className="container-site py-14 md:py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">Mobility Station · VAT relief</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-extrabold leading-[0.98] tracking-[-0.045em] text-primary md:text-6xl lg:text-7xl">Pay the right price.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted md:text-xl">If you have a qualifying disability or chronic condition, eligible mobility products can be supplied without 20% VAT.</p><Link href="/shop" className="mt-8 inline-flex rounded-full bg-accent px-7 py-3 font-semibold text-accent-foreground hover:bg-accent-hover">Shop mobility products</Link></div></section>
    <section className="py-14 md:py-20"><div className="container-site max-w-5xl"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-[2rem] bg-primary p-7 text-white md:p-9"><ShieldCheck className="h-7 w-7 text-accent" /><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-accent">Who qualifies?</p><h2 className="mt-2 text-3xl font-extrabold">Long-term illness or disability.</h2><p className="mt-3 text-sm leading-relaxed text-white/70">Eligible disabled and chronically sick people can buy certain goods and services without paying VAT.</p><div className="mt-7 grid gap-2 sm:grid-cols-2">{qualifyingConditions.map((c) => <div key={c} className="flex items-start gap-2 text-sm text-white/80"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" /><span>{c}</span></div>)}</div><p className="mt-6 text-sm text-white/65">Unsure? <Link href="/contact" className="font-semibold text-white underline">Contact us</Link>.</p></div><div className="rounded-[2rem] border border-border bg-soft/55 p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">How it works</p><h2 className="mt-2 text-3xl font-extrabold text-primary">Three simple steps.</h2><div className="mt-7 space-y-6">{[["01","Select VAT relief","At checkout, choose the VAT relief option."],["02","Complete the declaration","Confirm the qualifying condition and HMRC declaration."],["03","Pay the VAT-free price","Eligible VAT is removed from the order total."]].map(([step,title,desc]) => <div key={step} className="flex gap-4"><span className="text-xs font-bold text-muted">{step}</span><div><h3 className="font-bold text-primary">{title}</h3><p className="mt-1 text-sm text-muted">{desc}</p></div></div>)}</div></div></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-white p-6 md:p-8"><div className="flex items-start gap-4"><FileText className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><h2 className="text-xl font-bold text-primary">The declaration</h2><blockquote className="mt-4 border-l-2 border-accent pl-4 text-sm italic leading-relaxed text-muted">“{VAT_DECLARATION}”</blockquote><p className="mt-3 text-sm text-muted">Required by HMRC. We retain a copy of VAT relief declarations.</p></div></div></div><div className="rounded-2xl border border-border bg-white p-6 md:p-8"><div className="flex items-start gap-4"><AlertTriangle className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><h2 className="text-xl font-bold text-primary">Important</h2><p className="mt-3 text-sm leading-relaxed text-muted">A false declaration to claim VAT relief is a <strong className="text-foreground">criminal offence</strong>. VAT relief is only for customers who genuinely meet the qualifying rules.</p></div></div></div></div>
      <div className="mt-14"><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Common questions</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-primary md:text-4xl">VAT relief FAQs</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{faqs.map((faq) => <div key={faq.q} className="rounded-2xl border border-border bg-white p-6"><h3 className="flex items-start gap-2 font-bold text-primary"><HelpCircle className="mt-0.5 h-4 w-4 shrink-0" />{faq.q}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{faq.a}</p></div>)}</div></div>
    </div></section>
    <CtaFooter title="Need help with VAT relief?" />
  </>;
}
