import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import EnquiryForm from "@/components/EnquiryForm";
import { displayPrice, gbp, getProduct, getProducts } from "@/lib/catalog";

export const dynamic="force-dynamic";
const editorial: Record<string,{title:string;description:string;heading:string;intro:string;sections:{h:string;p:string}[]}>={
  "self-balancing-wheelchairs":{title:"Self-Balancing Wheelchairs UK | XSTO M4 Series | KLYM",description:"Discover XSTO self-balancing powered wheelchairs including the M4, M4B and M4 Pro.",heading:"Self-balancing mobility, explained.",intro:"The XSTO M4 family uses active balancing technology to create a compact powered mobility platform with a distinctive, controlled driving experience.",sections:[{h:"Why self-balancing?",p:"The balancing platform is designed to manage pitch continuously while the chair moves, helping XSTO keep a compact wheelbase and manoeuvre precisely."},{h:"Which model should I look at?",p:"The M4 is the original everyday model, the M4B is the latest evolution with revised front wheels and a folding footrest, while M4 Pro adds a more premium specification."},{h:"Try it rather than guess",p:"Self-balancing mobility feels different from a conventional powered wheelchair. A demonstration is the best way to understand how it behaves for you."}]},
  "stair-climbing-wheelchairs":{title:"Stair-Climbing & All-Terrain Wheelchairs UK | XSTO X12 | KLYM",description:"Explore XSTO X12 and X12 Pro all-terrain powered mobility technology with KLYM Mobility.",heading:"Go beyond ordinary powered mobility.",intro:"The XSTO X12 range is the specialist end of the KLYM line-up, built for demanding terrain and advanced access requirements.",sections:[{h:"X12 or X12 Pro?",p:"Both sit above the M4 family when terrain and advanced mobility are the priority. The X12 Pro is the flagship version."},{h:"Suitability matters",p:"Advanced terrain and step/stair capability requires the right assessment, environment and user training. We recommend discussing your intended use before purchase."},{h:"UK advice and demonstration",p:"KLYM can help you compare the X12 models, understand VAT relief and arrange the right demonstration path."}]},
  "vat-relief":{title:"VAT Relief on Powered Wheelchairs | KLYM Mobility",description:"A straightforward guide to VAT relief for eligible disabled customers purchasing qualifying powered mobility products.",heading:"VAT relief, without the confusion.",intro:"Qualifying mobility products may be supplied at 0% VAT to eligible chronically sick or disabled customers when the legal conditions and declaration requirements are met.",sections:[{h:"Who can qualify?",p:"Eligibility depends on the customer and the intended personal use of the qualifying product. The relief is not simply an age-based discount."},{h:"Why KLYM shows VAT-relief pricing",p:"Our core XSTO products are mobility products commonly purchased by eligible customers, so we show the VAT-relief price prominently while keeping eligibility clear."},{h:"We will verify before completion",p:"Before a VAT-relieved sale is completed, the required eligibility declaration and order details need to be captured correctly."}]}
};

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;if(editorial[slug]){const e=editorial[slug];return {title:e.title,description:e.description,alternates:{canonical:`https://klym.co.uk/${slug}`}}}const product=await getProduct(slug);if(!product)return {title:"KLYM Mobility"};return {title:`XSTO ${product.shortName} UK | KLYM Mobility`,description:product.meta_description||product.description||`Discover the XSTO ${product.shortName} from KLYM Mobility.`,alternates:{canonical:`https://klym.co.uk/${product.slug}`}}}

export default async function SlugPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const e=editorial[slug];if(e)return <main className="page-shell"><section className="page-hero"><p className="eyebrow plain">KLYM GUIDE</p><h1>{e.heading}</h1><p>{e.intro}</p></section><section className="content-section narrow">{e.sections.map(s=><div key={s.h} style={{marginBottom:42}}><h2>{s.h}</h2><p>{s.p}</p></div>)}<div className="cta-row"><Link className="btn blue" href="/compare">Compare XSTO models →</Link><Link className="btn outline" href="/book-a-demo">Book a demo</Link></div></section></main>;
 const found=await getProduct(slug);if(!found)notFound();const product=found!;const price=displayPrice(product);const highlights=(product.features&&product.features.length?product.features:["UK specialist support","VAT relief available if eligible","Free UK mainland delivery","Book a demonstration"]).slice(0,6);const specs=product.specifications&&typeof product.specifications==="object"?Object.entries(product.specifications).slice(0,9):[];const products=await getProducts();const related=products.filter(p=>p.slug!==product.slug).slice(0,4);const structured={"@context":"https://schema.org","@type":"Product",name:`XSTO ${product.shortName}`,brand:{"@type":"Brand",name:"XSTO"},description:product.description,image:product.image_url?[product.image_url]:undefined,sku:product.sku||undefined,offers:{"@type":"Offer",priceCurrency:"GBP",price:String(price),availability:"https://schema.org/InStock",url:`https://klym.co.uk/${product.slug}`}};
 return <main className="page-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured)}}/><section className="product-page"><div className="product-top"><div className="product-media"><img src={product.image_url||undefined} alt={`XSTO ${product.shortName}`} /></div><div className="product-copy"><p className="product-kicker">XSTO MOBILITY</p><h1>{product.shortName}</h1><p className="lede">{product.description}</p><div className="product-price">{gbp(price)}</div><div className="vat-note">with VAT relief, subject to eligibility</div><div className="product-highlights">{highlights.map((h,i)=><span key={i}>✓ {typeof h==="string"?h:JSON.stringify(h)}</span>)}</div><div className="cta-row"><Link className="btn blue" href={`/book-a-demo?product=${encodeURIComponent(`XSTO ${product.shortName}`)}`}>Book a demo →</Link><a className="btn outline" href="#enquire">Ask about buying</a></div></div></div></section>{specs.length>0&&<section className="content-section"><p className="eyebrow plain">KEY SPECIFICATIONS</p><h2>XSTO {product.shortName} at a glance.</h2><div className="spec-grid">{specs.map(([k,v])=><div className="spec-card" key={k}><b>{k.replaceAll("_"," ")}</b><span>{typeof v==="string"||typeof v==="number"?String(v):JSON.stringify(v)}</span></div>)}</div></section>}<section className="content-section" id="enquire"><div className="form-wrap"><div><p className="eyebrow plain">BUY OR DEMO</p><h2>Talk to a KLYM XSTO specialist.</h2><p>Ask about availability, VAT relief, delivery or arranging a demonstration. This enquiry goes directly into the Mobility Station V1 backend.</p></div><EnquiryForm defaultProduct={`XSTO ${product.shortName}`} type="sales"/></div></section><section className="range-section"><div className="section-heading"><div><p className="eyebrow plain">ALSO CONSIDER</p><h2>Compare the range.</h2></div><Link className="btn outline small" href="/compare">Compare all →</Link></div><div className="product-grid">{related.map(p=><Link className="product-card" href={`/${p.slug}`} key={p.slug}><div className="product-image"><img src={p.image_url||undefined} alt={p.name}/></div><h3>{p.shortName}</h3><p>{p.description?.split(".")[0]}.</p><strong>From {gbp(displayPrice(p))}</strong><small>with VAT relief</small><span className="card-arrow">→</span></Link>)}</div></section></main>}
