-- Prepared only: live execution was declined by the database tool.
-- Retailer confirms 150kg capacity and advertised estimates of 8/16/24 miles.
UPDATE public.stock_items SET
 specifications = '{"Weight (without battery)":"24.8 kg","Battery weight":"1.7 kg each","Weight Capacity":"150 kg","Open dimensions (L × W × H)":"101 × 60 × 93 cm","Folded dimensions (L × W × H)":"64 × 34 × 74 cm","Seat width":"45 cm","Seat depth":"43 cm","Seat to floor":"48 cm","Width between armrests":"49 cm","Backrest width":"44 cm","Armrest to seat":"21 cm","Motor Power":"2 × 250W, DC 24V brushless","Battery Type":"24V 10Ah lithium, up to 3 batteries","Advertised range — 1 battery":"Up to 8 miles","Advertised range — 2 batteries":"Up to 16 miles","Advertised range — 3 batteries":"Up to 24 miles","Max Speed":"6 km/h (approx. 3.7 mph)","Maximum gradient":"15°","Turning Radius":"85 cm","Ground Clearance":"6.3 cm","Wheelbase":"65 cm","Braking distance":"1 m","Front Wheel Size":"8 × 2 inch PU","Rear Wheel Size":"12 inch","Frame":"Aluminium","Armrests":"Flip-up with soft PU pads","Anti-tip wheels":"Foldable","Seat cushion":"10 cm","Upholstery":"Nylon, tension-adjustable seat and back","Charger output":"24V / 2A","Charger input":"100–240V, 50/60Hz","Charging time":"3–4 hours"}'::jsonb,
 description = 'The ErgoFold Elite is a folding aluminium electric wheelchair with twin 250W brushless motors and a 24V 10Ah lithium battery system that supports up to three batteries. Advertised range is up to 8 miles with one battery, 16 miles with two or 24 miles with three. Actual range varies with user weight, terrain, temperature and driving style.

The chair weighs 24.8kg without batteries; each battery weighs 1.7kg. Open dimensions are 101 × 60 × 93cm (L × W × H), folding to 64 × 34 × 74cm. Maximum user weight is 150kg for our ErgoFold Elite configuration. Flip-up padded armrests, an adjustable nylon seat and back, and foldable anti-tip wheels complete the practical design.',
 weight = 24.8,
 features = ARRAY['Advertised range estimates: up to 8 / 16 / 24 miles with 1 / 2 / 3 batteries. Actual range varies.','24.8kg without batteries; 1.7kg per battery.','Open 101 × 60 × 93cm; folded 64 × 34 × 74cm.','Twin 250W, 24V brushless motors.','150kg maximum user weight.','85cm turning radius; 6.3cm ground clearance.'],
 meta_description = 'ErgoFold Elite folding electric wheelchair. 24.8kg without batteries, 150kg capacity and advertised ranges up to 8, 16 or 24 miles.'
WHERE id = 'bcabc0e5-eba0-4c7f-9b75-19d78010be9b';
